apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogger-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogger-pro
  template:
    metadata:
      labels:
        app: blogger-pro
    spec:
      hostNetwork: true
      containers:
        - name: blogger-pro
          image: localhost:5001/blogger-pro:$BUILD_NUMBER
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m
          ports:
            - name: frontend-port
              containerPort: 8000
            - name: backend-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: blogger-pro
spec:
  ports:
    -
      port: 8000
    -
      port: 3000
  selector:
    app.kubernetes.io/name: blogger-pro
