apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogger-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogger-pro
  template:
    metadata:
      labels:
        app: blogger-pro
    spec:
      hostNetwork: true
      containers:
        - name: blogger-pro
          image: localhost:5001/blogger-pro:{{BUILD_NUMBER}}
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 700Mi
              cpu: 300m
          ports:
            - name: blogger-pro-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: blogger-pro
spec:
  ports:
    - name: blogger-pro-port
      port: 3000
  selector:
    app.kubernetes.io/name: blogger-pro
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogger-pro-ingress
spec:
  defaultBackend:
    service:
      name: blogger-pro
      port:
        number: 8000
