---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogger-pro-frontend-ingress
spec:
  defaultBackend:
    service:
      name: blogger-pro
      port:
        number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogger-pro-backend-ingress
spec:
  defaultBackend:
    service:
      name: blogger-pro
      port:
        number: 3000
